In [11]:
import numpy as np
import pandas as pd

In [12]:
df=pd.read_csv("Uttar_Pradesh.csv")

In [13]:
df

Year    BJP    INC     SP    BSP   RLD
0  2012  15.00  11.63  29.15  25.91  2.33
1  2014  42.63   7.53  22.35  19.77  0.86
2  2017  39.67   6.25  21.82  22.23  1.78
3  2019  49.98   6.36  18.11  19.43  1.69
4  2022  41.60   2.40  32.30  13.00  2.90

In [14]:
from sklearn.svm import SVR

In [15]:
model=SVR(kernel='rbf')
model.fit(df[['Year']],df['BJP'])
y_predict=model.predict([[2024]])
y_predict

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(


array([41.35918612])

In [16]:
odel=SVR(kernel='rbf')
model.fit(df[['Year']],df['SP'])
y_predict=model.predict([[2024]])
y_predict

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(


array([23.4481228])

In [17]:
model=SVR(kernel='rbf')
model.fit(df[['Year']],df['INC'])
y_predict=model.predict([[2024]])
y_predict

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(


array([6.09946931])

In [18]:
model=SVR(kernel='rbf')
model.fit(df[['Year']],df['RLD'])
y_predict=model.predict([[2024]])
y_predict

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(


array([2.84889254])

In [19]:
model=SVR(kernel='rbf')
model.fit(df[['Year']],df['BSP'])
y_predict=model.predict([[2024]])
y_predict

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(


array([18.80667292])

In [20]:
#SWING
BJP:-0.25
INC:-0.36
SP:5.33
BSP:5
RLD:0